### ISSUE TITLE
Missing value in e-mail

### ISSUE THREAD

**Issue by mirsafari** [ServerCentral/praeco#58]
In the e-mail alert type, some values are shown as missing, but they are displayed correctly in praeco UI like on pictures. Note: I'm using "Use terms query" option.
Email:
![bug_email](https://user-images.githubusercontent.com/16070956/48195368-bf86bc80-e34f-11e8-9c5e-6b93a8f6422d.png)
UI display:
![bug_email2](https://user-images.githubusercontent.com/16070956/48195373-c6adca80-e34f-11e8-942c-4de42c78b88b.png)
Is it maybe because query for alert does not get all values, but only the one specified in query_key (GROUPED OVER), since the value under docker.container.name is displayed correctly? But why would than UI display be correct? 
Thanks for the explanation!

**Comment by johnsusek** [comment]
Yes, you're right, since it is grouped, it cannot get these values from the query. 

The UI just fetches the most recent record matching your query and replaces the values (I am doing the templating myself). It doesn't use the internal elastalert templating. 

So I will have to add logic to limit what the available terms you can insert into subject/body, when you are using a grouped query.

**Comment by johnsusek** [comment]
Fixed, will be in next release. The templating preview in praeco will now only allow for inserting the grouped over field, to match the elastalert templating
